### ISSUE TITLE
Define how captchas fail in YAML

### ISSUE THREAD

**Issue by Hainish** [unitedstates/contact-congress#1288]
Currently, the last part of a MoC YAML file is the <i>success criteria</i>.  If a form fill encounters an `error` or a `failure`, the congress-forms server will be able to report that's what we see.  However, if a captcha failure message appears, all we'll currently be able to determine is that we did not see the success message, which will result in a `failure`.  Or, if the last step is `find`, we'll send an `error` status.

If we define how captcha's fail in the YAML, we'll be able to report back to the frontend a status of `captcha_failed`.  This means that the frontend can safely send a second fill request, without concern of sending one or more duplicates.  Right now, if we see a failure, we can send follow-up requests to hope for a `success` next time.  If the form starts failing for reasons unrelated to the captcha (say the form CSS has changed), we may be sending duplicates and we wouldn't be able to tell.  We also wouldn't know we need to fix the form, and may assume it's a problem with users filling in captcha's incorrectly.  If we define how captcha's fail, we will be able to tell.  I suspect this can be built in with low overhead, as we currently only have 13 MoC with captchas.

The following format may work:

<pre>
  - captcha_failure_criteria:
    - selector: "h3.red"
      value: "Sorry, you did not enter the correct captcha."
</pre> 

@sinak, @drinks, what do you think?

**Comment by koryp123** [comment]
Does anyone know how many member of Congress have Captchas at the moment?  I saw above that it's 13, but that was three yrs ago.
Thanks

**Comment by j-ro** [comment]
One Senator has a captcha, the others have recaptchas (entire house, which is why you use CWC instead) and about 5 Senators.
