### ISSUE TITLE
[E000294] Rep. Tom Emmer

### ISSUE THREAD

**Issue by rshorey** [unitedstates/contact-congress#1322]
Newly elected to 114th congress

**Comment by j-ro** [comment]
I'm kind of stumped on this one. Someone want to take a look? It's a very common CMS, so gotta figure it out.

As far as I can tell, the submit button never actually gets clicked.

**Comment by j-ro** [comment]
Hm...it may be just this one actually. Others with this CMS are passing, so that's good at least.

**Comment by j-ro** [comment]
update here -- about a quarter work from this CMS, but a quarter don't. For example, M001197 works just fine, even though the setup is identical to this one and other failing ones. No idea why. Skipping for now, but will have to dig in soon, so if someone has ideas, let me know!

**Comment by j-ro** [comment]
I think I've got it! We need to send the click event twice. No idea why, but it works for this one anyway, and consistently. Will be trying the others shortly.

**Comment by sinak** [comment]
Hah, nice one @j-ro! Weird one, though - hope it works for the other quarter using the same CMS.

**Comment by j-ro** [comment]
so far so good! Just put up the fix for the rest of em, so we'll see.
