### ISSUE TITLE
[P000610] Rep. Stacey Plaskett

### ISSUE THREAD

**Issue by rshorey** [unitedstates/contact-congress#1341]
Newly elected to 114th congress

**Comment by j-ro** [comment]
note, I'm not going to be able to test this yaml because our system currently is only set up to send messages to voting members.

**Comment by crdunwel** [comment]
cleaning up old issues - this has been resolved https://github.com/unitedstates/contact-congress/commit/3d9ad0a415ed9efef200e4b924c06826fadf0cf4
