### ISSUE TITLE
[G000575] Rep. Gwen Graham

### ISSUE THREAD

**Issue by rshorey** [unitedstates/contact-congress#1357]
Newly elected to 114th congress

**Comment by j-ro** [comment]
Here's another stumper. When I fill out this form, after clicking the submit button on the second step I apparently get transported to the office list page somehow:

https://can2-dev.s3.amazonaws.com/development/screenshots/356430b4c952371c94a44149d5.png

I've tested this a bit, and we definitely make it down to the submit button with all the data in the right place. Clicking the submit button somehow makes us leave the form. 

Maybe there's some kind of display bug and the offices link right below is overlapping the submit button somehow (though I didn't see that on my intentionally broken versions so I could see how far down the form we were getting: https://can2-dev.s3.amazonaws.com/development/screenshots/5d7602716623f99984204b5eea.png). 

This might be one I try with webkit, to see if it makes a difference. Very weird.

**Comment by j-ro** [comment]
Same thing happening for #1325

**Comment by j-ro** [comment]
works with webkit!
