### ISSUE TITLE
E000295 is empty

### ISSUE THREAD

**Issue by bwestergard** [unitedstates/contact-congress#1401]
https://github.com/unitedstates/contact-congress/blob/master/members/E000295.yaml

**Comment by j-ro** [comment]
all senator yamls for the new congress are empty right now because they lack websites (and thus contact forms).

**Comment by bwestergard** [comment]
What is the value in having the empty files?

**Comment by j-ro** [comment]
They were algorithmically created for everyone elected in the new congress. They will be filled once the senators have websites. For now, they stand as placeholders, and I guess accurately represent the state of that senator's webform...
