### ISSUE TITLE
[P000592] Ted Poe Options Formatting

### ISSUE THREAD

**Issue by y2mq37** [unitedstates/contact-congress#1417]
Victims Rights under options in Ted Poe's page reads:

Victimâ€™s Rights: WEBVIC

https://github.com/unitedstates/contact-congress/blob/master/members/P000592.yaml

Not sure if that formatting is intentional, but I figured I'd point it out.

**Comment by crdunwel** [comment]
Thank you. It's an encoding thing that his developers did wrong. See http://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC%E2%84%A2-showing-on-page-instead-of

The yaml is working so going to close this issue.
