### ISSUE TITLE
[P000592] no $ADDRESS_ZIP_PLUS_4 field on form

### ISSUE THREAD

**Issue by rubbingalcoholic** [unitedstates/contact-congress#1418]
The [contact form for Congressman Ted Poe](https://poe.house.gov/index.cfm/contact-form#form_D05B44B5-B782-4DC7-BED6-FF0C90951FFF) has two separate inputs for zip code. One for the 5 digit portion ($ADDRESS_ZIP5) and another for the 4 digit extension ($ADDRESS_ZIP4)

The P000592.yaml file erroneously contains a required variable marked $ADDRESS_ZIP_PLUS_4. According to the [variables.yaml](https://github.com/unitedstates/contact-congress/blob/master/support/variables.yaml) this should only be used for fields that require the user to input the concatenated zip+4 entry themselves.

This issue could be solved by renaming the $ADDRESS_ZIP_PLUS_4 in Poe's yaml file to $ADDRESS_ZIP4. I would do it myself but this is my first suggestion and I want to make sure I'm not missing something.

**Comment by j-ro** [comment]
You're absolutely right! Want to submit a pull request with that fix?

**Comment by j-ro** [comment]
merged, thank you!

**Comment by lucyq7** [comment]
YAML file lost. I am working on it.
