### ISSUE TITLE
Form in an iframe

### ISSUE THREAD

**Issue by kthayer424** [unitedstates/contact-congress#1421]
Some people on the state level hide the form on their page in an iframe. This is a bit of a problem because PhantomJS (and other browsers) need to switch to the iframe before being able to access elements in that iframe. Usually this is easy to circumvent by visiting the source of the iframe instead of the parent frame and filling in the information. But for at least one governor this strategy won't do. 

The problem form is located [here](http://www.governor.state.nm.us/Contact_the_Governor.aspx) and the iframe's source is [here](http://www.governor.state.nm.us/uploads/FreeForm/45fc5ace1ee4466fbeccdc16f83084f7/) which, if visited, will 403.

I'd like to propose a modest schema change to add an iframe element. It would looks something like:

```
- iframe:
  - name:
    selector:
    back:
```

This would give us the selector needed to switch frames in the headless browser we're using to access the underlying elements. I'm definitely open to other options to get around this problem also, so feel free to share any feedback.

The `back` property was added to signify that you want out of the iframe, back into the parent frame. It is optional and doesn't need a selector.

**Comment by j-ro** [comment]
Note, for this I'm using an email for the governor. 

But yes, an iframe selector could be useful. Another way would be to have some kind of header selector -- this iframe requires a referrer header from http://www.governor.state.nm.us/, so if we spoof the header, we'll get in.
