### ISSUE TITLE
[M000702] No click on FF, needs webkit but webkit crashes

### ISSUE THREAD

**Issue by j-ro** [unitedstates/contact-congress#1435]
Anyone have any thoughts on M000702? 

It seems to need webkit -- without it, we have that double click on the submit button issue. But with it, we get a broken pipe webkit crash.

It may be related to this: https://github.com/thoughtbot/capybara-webkit/issues/674

Haven't tried that yet. I wish we knew better why this click thing happened -- a double submit button click does indeed work. But that's not a good solution.

**Comment by Hainish** [comment]
I've opened an issue on the `capybara-webkit` project with an isolated example of the issue.

https://github.com/thoughtbot/capybara-webkit/issues/782

**Comment by Hainish** [comment]
I fix this by adding a "javascript" instruction as discussed previously (I can't find the issue # but I think we agreed on this?)

**Comment by j-ro** [comment]
Yeah, I think javascript is super useful. Can you document in the yaml spec?

**Comment by Hainish** [comment]
yes - I'll do that now

**Comment by Hainish** [comment]
done - https://github.com/unitedstates/contact-congress/commit/29d00e1d00f57947ffbff349bc9e8b38f15e57ad

**Comment by csnardi** [comment]
No longer in Congress, closing.
