### ISSUE TITLE
[R000582] Two "contact_form" keys breaks some YAML parsers

### ISSUE THREAD

**Issue by biwashingtonial** [unitedstates/contact-congress#1439]
R000582.yaml contains two _contact_form_ keys. This means parsers that comply with the YAML spec will catch only the steps contained in the first _contact_form_ and will ignore the rest.

**Comment by j-ro** [comment]
That looks like a mistake to me -- feel free to submit a PR to correct it.

**Comment by biwashingtonial** [comment]
I have a patch ready. GitHub is denying me access to push it.

**Comment by j-ro** [comment]
Right, can you submit it as a pull request?

**Comment by biwashingtonial** [comment]
https://github.com/unitedstates/contact-congress/pull/1440
