### ISSUE TITLE
former members of congress still in thing

### ISSUE THREAD

**Issue by timball** [unitedstates/contact-congress#1461]
G000569
N000186
S0001179

those three are no longer members but still have contact yaml forms ... probably should yank .

--timball

**Comment by j-ro** [comment]
Yep, probably should be removed, want to submit a PR?

**Comment by blklane** [comment]
I can

**Comment by blklane** [comment]
I assume you meant `S001179`? The one above I was unable to find in the repo and seemed to have an extra `0`.

**Comment by lucyq7** [comment]
I am working on it.

**Comment by lucyq7** [comment]
YAML file lost. I am working on it.
