### ISSUE TITLE
Virginia scraper struggling with addition of - Elect after names of reps

### ISSUE THREAD

**Issue by Deskimo** [unitedstates/contact-congress#1516]
With a recent election some members still have - Elect after their name at source. This seems too be tripping up the scraper whereby it is putting Elect into the Last Name and leaving the First Name with the - and often the full name.

Though on one occasion the Full Name was placed in the Last Name. 

see ... 
![screen shot 2016-01-27 at 9 40 04 pm](https://cloud.githubusercontent.com/assets/8793431/12610972/9f9544d2-c53e-11e5-8d09-efff63f0ad5d.png)

Similar issues occurred in the House of Delegates

![screen shot 2016-01-27 at 9 41 30 pm](https://cloud.githubusercontent.com/assets/8793431/12611039/d318bf00-c53e-11e5-9051-60f8cc6834b1.png)

**Comment by j-ro** [comment]
I'm not sure why this comment is in this repo -- this repo concerns itself with YAML files of members of congress, to allow them to be filled electronically. It does not deal with scraping state-level data.

**Comment by Deskimo** [comment]
Sorry, pasted into wrong project issue tracker, I've deleted content as i can't delete the issue itself.

**Comment by j-ro** [comment]
no prob!
