### ISSUE TITLE
Leahy's form not working

### ISSUE THREAD

**Issue by konklone** [unitedstates/contact-congress#1524]
Our code for Leahy's form appears to have stopped working.

This is what the input constraints should be:

```
input_A815013C-5056-A066-60B1-194269FB0FE0: <PREFIX – valid prefixes listed below>
input_36C9576F-5056-A066-6022-2CCEB276F085: <PREFIX – valid prefixes listed below>
input_E8922734-5056-A066-6013-55EC384EACB0: <leave blank, but must be present>
input_36F9116D-5056-A066-6055-B856B7975A8D: <FIRST NAME>
input_36F9168F-5056-A066-6010-D50B3E4EA5CA: <LAST NAME>
input_36D0D7B4-5056-A066-604B-C5784DE1329E: <ADDRESS LINE 1>
input_36D0D80C-5056-A066-60FD-FAC648288307: <ADDRESS LINE 2>
input_36D0D8E1-5056-A066-6088-B0E287342B26: <CITY>
input_36D0D97F-5056-A066-60F8-E619D2313E31: <TWO CHARACTER STATE CODE>
input_36D0DA1C-5056-A066-605E-9CA59C0D0E35: <5 DIGIT ZIP CODE>
input_36D667AA-5056-A066-6035-8576D66D00F9: <EMAIL 1>
input_36D6681A-5056-A066-60DC-988EFD5753D6: <EMAIL 2 - must match EMAIL 1 or submission will be rejected>
input_36D95985-5056-A066-6035-E42D9CB11A0E: <PHONE NUMBER>
input_36E22353-5056-A066-60EA-9A7BCE98E4DD: <ISSUE CODE - see provided list>
input_36E62F57-5056-A066-60BF-78ADF9F5676E: <BODY CONTENT>
creativengine_form_identifier:0CA3C0AF-5056-A066-6068-AD712CA6B58A   <INCLUDE THIS FIELD UNTOUCHED>
```

And this is the table of subjects:

| Value | Full String |
| --- | --- |
| AFGHANISTAN | Afghanistan |
| AGRICULTURE | Agriculture |
| AN | Animals |
| ARTS | Arts & Humanities |
| AUTO INDUSTRY | Auto Industry |
| BANK | Banking & Financial Services |
| BUDGET GENERAL | Budget |
| BUS | Business & Commerce |
| CIVIL_RIGHTS | Civil Rights |
| CLIMATE CHANGE | Climate Change |
| CRIME | Crime |
| DAIRY | Dairy |
| DEFENSE/MILITARY | Defense/Military |
| TORTURE | Detainee Treatment |
| DISABILITIES | Disability Issues |
| DRONES | Drones |
| ECONOMY | Economy |
| ED | Education |
| ELECTION | Elections & Voting Rights |
| LAB | Employment,  Labor & Pensions |
| EN | Energy |
| ENVIRONMENT | Environment |
| FR | Foreign Policy |
| FOSSIL FUELS | Fuel/Gas Prices |
| GENETICENGINEERING | Genetically Engineered Food (GMOs) |
| GUN CONTROL | Gun Control & Second Amendment Rights |
| HEALTH CARE REFORM | Health Care Reform |
| HEALTH/DISEASE | Health/Disease |
| HLS | Homeland Security |
| HOUSING | Housing |
| FEMA | Hurricane Irene |
| IMMIGRATION | Immigration |
| NOMINATIONS | Judicial Nominations |
| ENVIRONMENT | Keystone Pipeline |
| LAW ENFORCEMENT | Law Enforcement |
| MEDICARE | Medicare/Medicaid |
| OTHER | Other |
| COPYRIGHT | Patents & Copyright |
| PRESCRIPTION DRUGS | Prescription Drugs |
| POLITICS | Political Parties and Campaign Finance Reform |
| PRIVACY | Privacy |
| TECHNOLOGY | Science & Technology |
| SENIORS | Seniors |
| SMALL BUSINESS | Small Business |
| SS | Social Security |
| NASA | Space/NASA |
| TAX | Taxation |
| TELECOMM | Telecommunications |
| TRD | Trade |
| TRANS - GENERAL | Transportation |
| VETERANS | Veterans Affairs |
| VAWA | Violence Against Women Act |
| HMS | Human Services & Welfare |
| WOMEN | Women & Children |
| SCHEDULING | Request an appointment |
| THANK(FAN MAIL) | Send a Thank You |

**Comment by j-ro** [comment]
We're seeing successful fills today (many!) for leahy using the yaml in this repo.

**Comment by konklone** [comment]
@j-ro Okay -- the status indicator on the README for Leahy says it's 0% successful. Are the status buttons out of sync?

**Comment by j-ro** [comment]
Status buttons haven't worked for about a year. I think we should remove them. See #1528

**Comment by csnardi** [comment]
Closing this as his form is working (at least as of now).
