### ISSUE TITLE
M001196 confirmation selector needs repair

### ISSUE THREAD

**Issue by LukeJoeDavis** [unitedstates/contact-congress#1526]

**Comment by j-ro** [comment]
We're seeing no issues with this yaml, with many successful fills today. But feel free to submit a pull request if you believe something needs fixing and we can evaluate it.

**Comment by LukeJoeDavis** [comment]
I was just going to update the selector on submission.   Just as an easy test for future contributions.

**Comment by j-ro** [comment]
Sure, great! Please submit a PR and we'll merge it, assuming it passes all of our tests.
