### ISSUE TITLE
Status on https://theunitedstates.io/contact-congress/ is broken

### ISSUE THREAD

**Issue by magruder85** [unitedstates/contact-congress#1555]
Hi,

I've noticed that the status for each congressmen on this page is broken:

https://theunitedstates.io/contact-congress/

**Comment by j-ro** [comment]
The status relies on a testing system that hasn't been running in well over a year, hence the statuses have been broken for similar amounts of time. Given that this project has 100% working coverage at the moment, that page should probably just come down at some point.

**Comment by magruder85** [comment]
I just attempting testing my own congressmen (ryan costello) and I went to a page not found. So his site's changed it seems. Do I submit a new issue for that?

**Comment by j-ro** [comment]
Sure! Or go ahead and submit a patch for the YAML if you want.

**Comment by oregondean** [comment]
Hi All,

I'm new here.  

EmailCongress is offline due to the Sunlight Labs shut down.  Has there been a discussion on how to get it back up?  Or where/how to bring up another instance somewhere?


Best Regards,

Dean


--

Dean Suhr
21345 Miles Drive
West Linn, OR 97068
503-656-4808

What is MLD?: http://mldlink.info/MLDoverview <http://mldlink.info/MLDoverview>

**Comment by j-ro** [comment]
I've seen nothing, no -- though others run contact tools based off this repo, like EFF's: https://democracy.io/

**Comment by oregondean** [comment]
What would it take to get the testing system back up and running?

ds

**Comment by j-ro** [comment]
I don't know, I didn't ever run the system. But I believe it uses the companion project to this repo, https://github.com/EFForg/phantom-of-the-capitol, which anyone is welcome to run. I would doubt that specific project gets back up on its own though, it's probably something you or others would have to rebuild. Maybe Sunlight has the code on github somewhere.

**Comment by j-ro** [comment]
Oh, sorry, the testing system -- you really don't need it, or we don't anymore, so I don't think we'll be putting it back up again. See that link above -- you can set up phantom yourself and use that for testing.
