### ISSUE TITLE
Congress Forms Debugger Broken

### ISSUE THREAD

**Issue by jaredleekatzman** [unitedstates/contact-congress#1556]
Trying to access the ["Congress Forms Debugger"](http://efforg.github.io/congress-forms-test/) and the loading bars never finish. When I look at the Chrome console, the error I get is:
`XMLHttpRequest cannot load https://congressforms.eff.org//list-congress-members?debug_key=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://efforg.github.io' is therefore not allowed access. The response had HTTP status code 401.`

**Comment by j-ro** [comment]
This infrastructure is no longer run, so it will not work. You'll need to run it yourself. See https://github.com/EFForg/phantom-of-the-capitol
