### ISSUE TITLE
ThomasId support in the future?

### ISSUE THREAD

**Issue by hdavidkim** [unitedstates/contact-congress#1584]
Hi,

Will there also be thomasId support in the future? As in, it'll also be included as a field in the files? If not, is there a reason it won't be?

**Comment by j-ro** [comment]
There are no plans for this -- this repo is a repository of yamls that describe contact forms for members of congress, it is not a file on matching data for said members. You can look here for things like that: https://github.com/unitedstates/congress-legislator
