### ISSUE TITLE
issue with Lisa Murkowski form (M001153)

### ISSUE THREAD

**Issue by woldemariam** [unitedstates/contact-congress#1592]
the yaml file has this following javascript that throws an error

`document.querySelector('#form-B03E03FC-4040-F985-52CD-BCD7E00A8A6C').submit();`

this is because this element is a DIV and it does not have a submit method. Would it be ok to remove?

**Comment by j-ro** [comment]
yeah, think so, or could make it target the form

**Comment by woldemariam** [comment]
there are two issues with targeting the form. first issue is that if you submit the form like this 

`document.querySelector('#B03E03FC-4040-F985-52CD-BCD7E00A8A6C').submit()`

it will submit the form without doing  validation. the second issue is that right following this javascript step is a clikc_on step which does the submit. that will fail if the form has been submitted. so I think it the correct fix is the remove the javascript

**Comment by j-ro** [comment]
I think so too, seeing as this works now
