### ISSUE TITLE
M001183.yaml has duplicate key

### ISSUE THREAD

**Issue by woldemariam** [unitedstates/contact-congress#1657]
YAML spec in version 1.2 says that in a valid YAML file, mapping keys are unique.

M001183.yaml contains this mapping:

```
            Jobs and the Economy: INR
            Jobs and the Economy: JOBS
```

It is in the YAML because the webform itself has Jobs and the Economy twice. However, is it possible to remove one of them to have the YAML validate?

**Comment by j-ro** [comment]
This is an accurate representation of what's on this website unfortunately, so even though not valid, I think we need to let it stand. The file is working with our phantom install.
