### ISSUE TITLE
Chuck Schumer modal on page load (S000148.yaml)

### ISSUE THREAD

**Issue by woldemariam** [unitedstates/contact-congress#1658]
Chuck Schumer has added a pop up to his form. I think we need to add a step to clear the popup. You will need to make sure you delete the popupContact cookie to see the popup. 

https://www.schumer.senate.gov/contact/email-chuck

**Comment by j-ro** [comment]
I generally handle this by clearing CSS on the page, so the modal doesn't block anything: https://github.com/unitedstates/contact-congress/blob/9cbf5ace3efaa823508527cafee0bd1bb83fd6a6/members/D000624.yaml#L7

Want to submit a PR for Schumer with that command added?
