### ISSUE TITLE
[S001217] Sen. Rick Scott - Missing

### ISSUE THREAD

**Issue by sinak** [unitedstates/contact-congress#1678]
Looks like we're missing Senator Rick Scott of Florida from the dataset.

**Comment by j-ro** [comment]
None of the new Senators have websites yet. This is fairly typical, they take some time, though the shutdown may be making it slower. Most of the Senators do have emails up here: https://www.senate.gov/senators/contact

Romney's the only one missing any way to contact him electronically I believe.

**Comment by sinak** [comment]
Got it, I was about to say, it looks like he just has an email address published. I wonder what happens with this email address after the website goes up.

**Comment by j-ro** [comment]
We plan on replacing our delivery method with the contact form once it's up and we have a chance to make a yaml for it. We check every day to see if the website is up.

**Comment by sinak** [comment]
That's great, thanks @j-ro! Are you currently delivering via email?

**Comment by j-ro** [comment]
Yeah, we are, outside of Romney, though I honestly don't know if it'll ever get read. Senators typically don't have emails.
