### ISSUE TITLE
[P000603] Sen. Rand Paul

### ISSUE THREAD

**Issue by konklone** [unitedstates/contact-congress#228]
Sen. Rand Paul:
http://www.paul.senate.gov

Likely contact form URL to start with:
http://www.paul.senate.gov/?p=contact

**Comment by Hainish** [comment]
Hey @crdunwel, it looks like Sen. Paul has changed his form again.  Submissions aren't going through, can you take a look?

**Comment by blklane** [comment]
Looks like its changed a bit, now at this url: http://www.paul.senate.gov/connect/email-rand, will try to fix it myself

**Comment by IanLee1521** [comment]
Probably can close this since #1463 was merged?

**Comment by j-ro** [comment]
yep, yaml is working
