### ISSUE TITLE
[R000307] Sen. Pat Roberts

### ISSUE THREAD

**Issue by konklone** [unitedstates/contact-congress#504]
Sen. Pat Roberts:
http://www.roberts.senate.gov

Likely contact form URL to start with:
http://www.roberts.senate.gov/public/index.cfm?p=EmailPat

**Comment by j-ro** [comment]
I feel this one is broken due to png issues somehow, like grabbing the png doesn't work in the driver. @Hainish any thoughts? I tried a ton of things...

**Comment by j-ro** [comment]
or...maybe not -- maybe it's something about position. With some of my tries, I got screen captures of unrelated areas of the page.

**Comment by j-ro** [comment]
working again, due to the form behaving better.

**Comment by Hainish** [comment]
I still need the wait: 2 in order for `captcha-needed` not to return an image like so:

https://congress-forms.s3.amazonaws.com/production/captchas/2869f2a0ff1525d4837d3a85b6.png

**Comment by j-ro** [comment]
sure, feel free to add it -- I'm finding that the question mark is not a function of wait. Often, on page load, even in my browser, the image just does not load. Yesterday it was basically never happening on first load. Today it sometimes (more often than not) happens. Waiting does not make it load.

**Comment by Hainish** [comment]
In my testing yesterday adding `wait: 2` made it load consistently.  Beforehand it was never loading.

**Comment by j-ro** [comment]
sure, feel free to add -- my testing had it not helping, but it's not harmful to have it there.
